//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using state_machine;
using UnityEngine;

public class login_state:State
{
	public login_state(STATE_ID id,StateMachine machine):base(id,machine)
	{
		
	}
	public override void onEnter (State from_state)
	{
		Debug.Log ("hello this is login_state");
		//GameUIs.getInstance ().hide_all ();
		//if(GameUIs.getInstance().login_panel!=null)
		GameUIs.getInstance ().login_panel.SetActive (true);
	}
	public override void onLeave (State to_state)
	{
		//Debug.Log ("the login_state" + GameUIs.getInstance ().login_panel);
		GameUIs.getInstance ().login_panel.SetActive (false);
	}
}


