//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using state_machine;
using UnityEngine;

public class select_room_state:State
{
	public select_room_state(STATE_ID id,StateMachine machine):base(id,machine)
	{

	}
	public override void onEnter (State from_state)
	{
		Debug.Log ("hello this is select_room_state");
		//GameUIs.getInstance ().hide_all ();
		GameUIs.getInstance ().select_room_panel.SetActive (true);
	}
	public override void onLeave (State to_state)
	{
		GameUIs.getInstance ().select_room_panel.SetActive (false);
	}
}


