//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace EditorNode
{
	public class BaseNode
	{
		public Rect windowRect;
		public List<BaseNode> neighbors = new List<BaseNode>();
		public BaseNode (float x,float y)
		{
			this.windowRect = new Rect (x,y, 100f, 100f);
		}

		public void AddTarget(BaseNode target)
		{
			this.neighbors.Add (target);
		}

		public void DrawNode()
		{
		}

		public void DrawCurve()
		{
			for (int i=0; i<neighbors.Count; i++) {
				BaseNode n = neighbors[i];
				Vector3 start = GetCenterPosition();
				Vector3 end = n.GetCenterPosition();
				Handles.DrawBezier(start,end,start+Vector3.right*50,end+Vector3.left*50,Color.red,null,5.0f);
			}
		}

		public Vector3 GetCenterPosition()
		{
			return new Vector3 (this.windowRect.center.x, this.windowRect.center.y, 0);
		}
	}
}

