//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine.UI;

namespace UI_ManagerNS
{
	public class guiManager
	{
		private static guiManager _instance = null;
		public InputField explaination_text;
		private guiManager ()
		{
		}

		public static guiManager getInstance()
		{
			if (_instance == null) {
				_instance = new guiManager();
			}
			return _instance;
		}
	}
}

