//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace GlobalObjectNameSpace
{
	public class GlobalObjectManager
	{
		private GlobalObjectManager ()
		{
		}

		private static GlobalObjectManager gom = null;
		public List<GameObject> objects = new List<GameObject> ();

		public static GlobalObjectManager getInstance()
		{
			if (gom == null) {
				gom = new GlobalObjectManager();
			}
			return gom;
		}

	}
}

