//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace ResourcesUtilNS
{
	public class fashion
	{
		private static fashion _instance;
		public static fashion getInstance()
		{
			if (_instance == null)
				_instance = new fashion ();
			return _instance;
		}

		public GameObject get_sprite(string path)
		{
			GameObject instance = new GameObject ();
			Texture2D ui_texture = Resources.Load(path) as Texture2D;
			Sprite ui_sprite = Sprite.Create(ui_texture, new Rect(0f, 0f, ui_texture.width,ui_texture.height),new Vector2(0,0));

			instance.AddComponent<SpriteRenderer> ();
			SpriteRenderer render = instance.GetComponent<SpriteRenderer> ();
			render.sprite = ui_sprite;

			var bounds = render.sprite.bounds;

			instance.transform.localScale = new Vector3 (1.0f/bounds.size.x, 1.0f/bounds.size.y, 0.0f);
			return instance;
		}

		private fashion ()
		{
		}
	}
}

