//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using state_machine;
using UnityEngine;

public class hall_state:State
{
	public hall_state(STATE_ID id,StateMachine machine):base(id,machine)
	{
		
	}
	public override void onEnter (State from_state)
	{
		GameUIs.getInstance ().hall_panel.SetActive (true);
	}
	public override void onLeave (State to_state)
	{
		GameUIs.getInstance ().hall_panel.SetActive (false);
	}
}


